# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    #config.ssh.insert_key = false
    #config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    #config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
	config.vm.provision "shell", path: "bootstrap.sh"
	
	config.vm.define "centos0#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "centos0#{i}.testlab.local"
      node.vm.network "public_network", ip: "192.168.16.10#{i}"
      
	  node.vm.provider "virtualbox" do |vb|
        vb.name = "centos0#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
    
	end
  
  end

end
