# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  #number of node that need to deploy
  NodeCount = 1
  (1..NodeCount).each do |i|
    
	#ssh key-based authentication
	config.ssh.insert_key = false
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
	
	#If install VirtualBox Guest Additions set auto_update to "TRUE" or running command "vagrant vbguest --do install"
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
      config.vbguest.no_remote = true
    end
      	
	# run bootstrap script
	config.vm.provision "shell", path: "bootstrap.sh"
	
	#basic define vm
	config.vm.define "centos0#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "centos0#{i}.testlab.local"
      node.vm.network "public_network", ip: "192.168.16.10#{i}"
      
	  #provision resources to vm
	  node.vm.provider "virtualbox" do |vb|
        vb.name = "centos0#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
    
	end
  
  end

end
