# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  
  ### configuration parameters ###
  # which host port to forward box SSH port to
  #LOCAL_SSH_PORT = "2222"
  # Vagrant base box to use
  BOX_BASE = "centos/7"
  # name of box
  BOX_NAME = "centos"
  # amount of RAM for Vagrant box
  BOX_RAM_MB = "2048"
  # number of CPUs for Vagrant box
  BOX_CPU_CORE = "1"
  ### end configuration parameters ###
  
  # number of node to deploy
  NodeCount = 1

  (1..NodeCount).each do |i|
    config.ssh.insert_key = false
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
	config.vm.provision "shell", path: "bootstrap.sh"
	
	config.vm.define BOX_NAME"#{i}" do |node|
      node.vm.box = BOX_BASE
      node.vm.hostname = BOX_NAME"#{i}.testlab.local"
      node.vm.network "public_network", ip: "192.168.16.10#{i}"
      
	    node.vm.provider "virtualbox" do |vb|
        vb.name = BOX_NAME"#{i}"
        vb.memory = BOX_RAM_MB
        vb.cpus = BOX_CPU_CORE
      end
    
	end
  
  end

end
